### ISSUE TITLE
The file:  does not exist !

### ISSUE THREAD

**Issue by dongdong812** [pakjiddat/word-predictor#1]
When I run the example code in wordpredictor.pdf page 30 on my windows 11, R 4.1.3:
mg <- ModelGenerator$new(
name = "default-model",
desc = "1 MB size and default options",
fn = "def-model.RDS",
df = "input.txt",
n = 4,
ssize = 0.99,
dir = ed,
dc_opts = list(),
tg_opts = list(),
ve = ve
)
it results in:
Error in private$dm("The file: ", rfn, " does not exist !", md = -1, ty = "e") : 
  The file:  does not exist !

**Comment by pakjiddat** [comment]
I ran the above code but did not get an error. Did you run the following environment setup code before running the above code:

```
# Start of environment setup code
# The level of detail in the information messages
ve <- 0
# The name of the folder that will contain all the files. It will be
# created in the current directory. NULL implies tempdir will be used
fn <- NULL
# The required files. They are default files that are part of the
# package
rf <- c("input.txt")
# An object of class EnvManager is created
em <- EnvManager$new(ve = ve, rp = "./")
# The required files are downloaded
ed <- em$setup_env(rf, fn)
# End of environment setup code
```
