### ISSUE TITLE
Failure with dev evaluate

### ISSUE THREAD

**Issue by hadley** [pakjiddat/word-predictor#2]
When I render `features.Rmd` with dev evaluate I see:

```
Warning message:
In file("", "w+b") :
  cannot open file '/tmp/RtmpZpUGvo/Rf3a0a4169aeaa': No such file or directory
```

This error is coming from evaluate but appears to be because word-predictor is deleting the temporary directory. If I set `ve = 1` and patch `dm()` to use `stderr()` I see:

```
Copying file: test.txt to /tmp/RtmpZpUGvo ✔
Copying file: validate.txt to /tmp/RtmpZpUGvo ✔
Copying file: validate-clean.txt to /tmp/RtmpZpUGvo ✔
Copying file: test-clean.txt to /tmp/RtmpZpUGvo ✔
Reading '/tmp/RtmpZpUGvo/test-clean.txt' ✔
Reading '/tmp/RtmpZpUGvo/test.txt' ✔
Reading '/tmp/RtmpZpUGvo/validate-clean.txt' ✔
Reading '/tmp/RtmpZpUGvo/validate.txt' ✔
Removing the folder /tmp/RtmpZpUGvo ✔
```

And obviously deleting the temporary directory is a bad idea.

I plan on submitting evaluate to CRAN on Sept 16, so you'll have a couple of weeks after that to fix the problem.

**Comment by pakjiddat** [comment]
I have updated the directory removal code in features.Rmd and overview.Rmd. The errors are fixed.
